### PR TITLE
Fixes lost @rel_var when branching QueryProxy

### LINKED ISSUE #1676: Lost @rel_var alias when using `QueryProxy#branch`
Using #branch causes the @rel_var of the initial QueryProxy to be lost

### 
`@history.students(:student, :enrolledIn).rel_var => :enrolledIn`

`@history.students(:student, :enrolledIn).branch { all }.rel_var => :rel2`

I suppose that bug is present in all versions.

### PR DESCRIPTION
**Pull request by lkalwa**
Fixes #1676

This pull introduces/changes:
 * propagates relationship alias when branching.  
 * implements #to_a with parameters on AssociationProxy

### CODE REVIEW

File: lib/active_graph/node/has_n.rb [hunk 1]
```diff
@@ -103,11 +111,11 @@ def init_cache
 
       def add_to_cache(object, rel = nil)
         (@cached_rels ||= []) << rel if rel
-        (@cached_result ||= []).tap { |results| results << object unless results.include?(object) }
+        (@cached_result ||= []).tap { |results| results << object if object && !results.include?(object) }
       end
 
       def rels
-        @cached_rels || super
+        @cached_rels || super.tap { |rels| rels.each { |rel| add_to_cache(nil, rel)  } }
```
Comment (klobuczek) [inline lib/active_graph/node/has_n.rb:118]: are you sure we are not losing here streaming potential?

**Review by klobuczek — APPROVED** [review]
